apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: demo
  labels:
    name: jee
spec:
  containers:
  - image: mysql:8
    name: mysql
    ports:
      - containerPort: 3306
        name: mysql
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-storage
    env:
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-admin
            key: username
      - name: MYSQL_DB
        valueFrom:
          secretKeyRef:
            name: mysql-admin
            key: database
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-admin
            key: password
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-admin
            key: password
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-data
