# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build appsrv with maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: cache maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: install ssh key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.BUILDACTION }}
    - name: create .ssh/known_hosts
      run: |
        ssh-keyscan -H -t rsa -v o.aberger.at  >> ~/.ssh/known_hosts

    - name: Build with Maven
      run: mvn -B package

    - name: Build docker images
      run: docker-compose build
      working-directory: docker

    - name: Deploy to server
      run: |
        scp appsrv/target/application-server-0.5.0-distribution.zip ubuntu@o.aberger.at:

